package com.shuao.NoteManagementAPI;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;

@DynamoDbBean
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String id;

    @DynamoDBAttribute
    private String dateCreated;

//    private String id;
//    private String dateCreated;

    public User(String id, String dateCreated) {
        this.id = id;
        this.dateCreated = dateCreated;
    }

//    @DynamoDbPartitionKey
//    @DynamoDbSecondaryPartitionKey(indexNames = "userID")
//    public String getDevice_id() {
//        return id;
//    }
//
//    public String getDateCreated() {
//        return dateCreated;
//    }

}
